### ISSUE TITLE
Creating and discovering themes

### ISSUE THREAD

**Issue by piccolbo** [thumbsup/theme-cards#4]
This is a little fuzzy and brainstorming level, if it doesn't make any sense please say so, I won't take it personally. Particularly @rprieto @amcolash since you are working on the wonderful new theme flow, you may have ideas about this, see #3.

One thing about naming themes and separate repos. With a view to encourage code reuse and contributing themes back. Is it fork-and-change the only approach we can provide? I have a fork of mosaic. Probably changed 20 lines in somewhat trivial ways. If anything is improved  or fixed in mosaic, I need to merge the changes, it may become difficult over time. Plus you can't merge from upstream with github UI, AFAIK, you need multiple git cmds. It'd be nice to enable non-coders to create small theme variants.

1. Is there any modularity in a theme? Is there a way to say: like mosaic, but I want a grey background? Copy and edit is almost never a good reuse strategy. For instance: allow overriding JS constants in a config? Overriding CSS?
2. Is there a way to contribute a theme back for the greater glory of thumbsup? Like a contrib theme directory or some such? Having a variety of themes available would boost thumbsup's appeal. Doing your own javascript and css, great for coders, but not the general public.

**Comment by rprieto** [comment]
Hi, great topics and ideas. Themes are quite new and I agree they can be improved.

1a. You can already override CSS (actually LESS) if the theme supports it. There is a basic example at https://thumbsup.github.io/docs/4-themes/themes/. For example the `mosaic` theme exposes `@highlight-color`, which I realise is not documented anywhere 😦

1b. It would be great to have even more flexibility with themes. There is an open issue at https://github.com/thumbsup/thumbsup/issues/137 about passing arbitrary options to themes, so that a theme can let the user control the slideshow speed, whether to display EXIF data, etc... Do you have any suggestions?

2. Right now there isn't but it would be nice. I agree fork-and-change isn't ideal. I can think of a few ideas:
- have some sort of convention so themes can be easily found on npm, like Grunt does with modules
- have a list of all known themes in the official docs
- make it so you can easily target *any* theme on github using a social syntax like `--theme repo/name`. This is tricky since à theme could require its own npm install.
- promote some themes to be official (hosted under `@thumbsup/theme-*` in npm, and bundle them in like Card or Mosaic.

We should look at how other platforms handle this, like Grunt plugins, Jekyll themes, etc...

**Comment by amcolash** [comment]
I think that for the referenced changes in #3, changing the visual styling of everything deserves a new theme.

I think that an ideal solution would be having some custom config options exposed as part of the json config file. That could be useful for things like specifying exif perferences, slideshow speed, etc.

As for styling, I think we should allow for a custom css file that can be loaded into any theme. In the base theme, it can load in a file if it is specified at site generation time.

I am basing part of this off of the [MagicMirror](https://github.com/MichMich/MagicMirror) project which has a similar concept of configurations + custom styling (if desired). There are not themes, but you can customize the base experience with custom options along the way.

I would also say that this issue should be migrated to the main thumbsup project as it is not specific to this theme, but for making a better themeing system in general.

**Comment by rprieto** [comment]
> we should allow for a custom CSS file

This is what `--theme-style` does. It allows you to add a LESS file applied on top of the theme, while also letting you override theme variables like `@highlight-color`.

Good idea about migrating. Because there's already another issue about passing options to themes, it looks like this one is becoming about better documentation and a system to find themes.

**Comment by piccolbo** [comment]
As far as opening issue here, spot on @amcolash rookie mistake on my part. I will reopen on thumbups repo.

**Comment by piccolbo** [comment]
Actually, I think I mostly reinvented the wheel here. What is left to do is

1. Document what each theme exposes and generally promote the override mechanism better
2. Theme discovery

The rest was custom CSS (available), theme options (under way) 

It sounds like two more focused issues for thumbsup main repo

**Comment by rprieto** [comment]
Thanks piccolbo, let's pick it up over there!

**Comment by amcolash** [comment]
> > we should allow for a custom CSS file
> 
> This is what `--theme-style` does. It allows you to add a LESS file applied on top of the theme, while also letting you override theme variables like `@highlight-color`.
> 
> Good idea about migrating. Because there's already another issue about passing options to themes, it looks like this one is becoming about better documentation and a system to find themes.

Had no clue that was baked in already @rprieto. I would say that would serve my own needs if I needed to theme! Thanks for the info. Thumbsup is pretty slick
