### ISSUE TITLE
Failure to generate pages with thumbnails

### ISSUE THREAD

**Issue by megahypercat** [thumbsup/theme-cards#5]
Page generation fails to link to correct thumbnails for albums.

![chrome_2019-10-19_00-18-50 1](https://user-images.githubusercontent.com/31746936/67131764-34bc6c00-f206-11e9-8f5f-6c75d68a7004.png)

The link to the image is correct EXCEPT it has backslash instead of forward slash. Maybe this is because I am on windows? Still, other themes work and editing this manually is not viable for hundreds of pages.

Changing the backshalsh to forward slash ( / ) makes it work.
![chrome_2019-10-19_00-34-19 1](https://user-images.githubusercontent.com/31746936/67132218-3c7d1000-f208-11e9-8cc3-cb0dd032196f.png)

Maybe switching
`      <a href="{{relative url}}" style="background-image: url('{{relative previews.0.urls.large}}')">`
in /theme/partials/content.hbs to 
`{{relative previews.0.urls.small}}`
Like in Flow would fix it. At least it would be good for bandwidth ( :

**Comment by aellwein** [comment]
Yes, same here. I use the cards theme and the thumbnail links are pointing to the large images, pretty annoying to load.

**Comment by rprieto** [comment]
Hi @megahypercat and @aellwein. I have merged the change to use `previews.0.urls.small` instead of `previews.0.urls.large`.

I'm glad it's working however it might be hiding a different issue on Windows. One of the reasons it could be broken is because the large version supports `--photo-preview resize | copy | symlink | link`. Which option are you using? Are the actual large photos (lightbox) working?

**Comment by aellwein** [comment]
Hi @rprieto, 
i don't use the config setting you mentioned, however, only viewing my albums on Linux or Mac.
The large photos are working just fine there.
